version: 2.1

orbs:
  general: edahlseng/general@1.20.0
  terraform-orb: bankrate/terraform@1.0.1

workflows:
  pipeline:
    jobs:
      - terraform-orb/fmt:
          name: tf-fmt
          infrastructure_dir: "${CIRCLE_WORKING_DIRECTORY}/terraform/files/droplet"
      - terraform-orb/validate:
          name: tf-validate
          infrastructure_dir: "${CIRCLE_WORKING_DIRECTORY}/terraform/files/droplet"
