version: 2.1

orbs:
  general: edahlseng/general@1.20.0
  terraform: bankrate/terraform@1.0.1

workflows:
  pipeline:
    jobs:
      - terraform-orb/fmt:
          name: tf-fmt
      - terraform-orb/validate:
          name: tf-validate
